### ISSUE TITLE
Cors disabled

### ISSUE THREAD

**Issue by Leonardo-Toledo-V** [GJZ26/Instagram-Clone#1]
You need to active CORS, because I am trying to make a request from a web page hosted on http://localhost:3000/ to a server running on http://localhost:3030/. However, the server is not configured to allow requests from this origin, so the browser is blocking the request.

To resolve this issue, you need to configure the server to include the 'Access-Control-Allow-Origin' header in the response. This header tells the browser which origins are allowed to make requests to the server. You can set the header to '*' to allow requests from any origin, or you can set it to specific origins.

- Install cors with npm:

```bash
npm i cors
```
- Then, on your `server.mjs` add this:

```plaintext
import express from 'express';
import cors from 'cors';
const app = express();
app.use(cors());
```

If you need more help for this issue, check [cors documentation](https://developer.mozilla.org/es/docs/Web/HTTP/CORS).
### Reading is a good practice to learn.

**Comment by GJZ26** [comment]
Fixed in pull request #4 
While it's a good idea what you're doing, I wish the policies were a little stricter. I hope it helps :)
