### ISSUE TITLE
Response SignUp

### ISSUE THREAD

**Issue by Leonardo-Toledo-V** [GJZ26/Instagram-Clone#2]
**When I make a request to `/auth/signup`**

*  **I send:**
```json
{
    "username":"CoolUser",
    "email":"coolme@mail.com",
    "password":"pAszW0rD%"
}
```
*  **You say the response is:**
```json
{
    "status":false,
    "data":{
        "message":"Ya existe una cuenta con éste correo electrónico o username"
    }
}
```

* **But in my Thunder Client I get this:**
```json
{
  "status": true,
  "data": {
    "message": "Ya existe una cuenta con éste correo electrónico o username"
  }
}
```
**I need the response false, to be able to validate if the user has already been created or not, Although the database does not save the data, it returns the status to true and it is incorrect.**

**Comment by GJZ26** [comment]
Fixed in pull request number: #3 
I hadn't noticed that little malevolent boolean.
Solution implemented and I hope it works perfectly in your tests.
